name: 🙋 Support-Anfrage
description: Bitte um Hilfe oder Klärung zu Setup, Nutzung oder Konfiguration im Profilmodul
labels: [question, support, profile]
body:
  - type: input
    id: context
    attributes:
      label: Betroffener Bereich
      placeholder: z. B. "GraphQL-Query getProfile", "Profil-Update", "Docker Setup"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Beschreibung des Problems
      description: Beschreibe, was nicht funktioniert und was du erwartest.
      placeholder: |
        - Ich habe `npm run start:dev` ausgeführt, aber Profil-Query gibt Fehler zurück
        - UI zeigt keine Social-Links an, obwohl diese im Backend gesetzt sind
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevante Fehlermeldungen oder Logs
      render: shell
      description: Kopiere relevante Logs oder Stacktraces hier rein (ohne sensible Daten).
    validations:
      required: false

  - type: dropdown
    id: env
    attributes:
      label: Umgebung
      options:
        - Lokal (Docker)
        - GitHub Actions
        - Kubernetes (Staging)
        - Kubernetes (Prod)
        - Andere
