name: ✅ Task
description: Eine kleine, klar definierte Aufgabe
labels: [task]
body:
  - type: input
    id: title
    attributes:
      label: Kurze Zusammenfassung
      placeholder: z. B. "Passe Button-Label in Profil-UI an"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Beschreibung
      description: Was muss getan werden? (Kurz und prägnant)
      placeholder: |
        - Entferne Inline-Styles und nutze Theme
        - Aktualisiere Profilbanner-Layout
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Bereiche
      options:
        - label: Frontend
        - label: Backend
        - label: Tests
        - label: Konfiguration
        - label: Dokumentation

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Akzeptanzkriterien
      description: Wann gilt die Aufgabe als abgeschlossen?
      placeholder: |
        - Button verwendet Styles aus Theme
        - Tests für neue UI-Komponente bestehen
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      options:
        - Hoch
        - Mittel
        - Niedrig
    validations:
      required: true
